ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/jquery@3.1.1/dist/jquery.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/js/bootstrap.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react@16.2.0/umd/react.production.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-dom@16.2.0/umd/react-dom.production.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-modal@3.1.10/dist/react-modal.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://cdn.plot.ly/plotly-2.11.1.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/sjcl@1.0.7/sjcl.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/layout-bin-packer@1.4.0/dist/layout-bin-packer.js.map
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading http://d3js.org/d3.v3.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://d3js.org/d3-selection-multi.v1.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/save-svg-as-png@1.4.17/lib/saveSvgAsPng.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-resizable@1.4.6/css/styles.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-grid-layout@0.16.3/css/styles.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/css/bootstrap.min.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/classnames@2.2.5
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/layout-bin-packer@1.4.0/dist/layout-bin-packer.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.eot
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.woff2
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.woff
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.ttf
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
INFO:root:Application Started
INFO:root:Working directory: /Users/maksimnovozhilov/.visdom
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/jquery@3.1.1/dist/jquery.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/js/bootstrap.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react@16.2.0/umd/react.production.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-dom@16.2.0/umd/react-dom.production.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-modal@3.1.10/dist/react-modal.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://cdn.plot.ly/plotly-2.11.1.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/sjcl@1.0.7/sjcl.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/layout-bin-packer@1.4.0/dist/layout-bin-packer.js.map
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading http://d3js.org/d3.v3.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://d3js.org/d3-selection-multi.v1.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/save-svg-as-png@1.4.17/lib/saveSvgAsPng.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-resizable@1.4.6/css/styles.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-grid-layout@0.16.3/css/styles.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/css/bootstrap.min.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/classnames@2.2.5
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/layout-bin-packer@1.4.0/dist/layout-bin-packer.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.eot
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.woff2
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.woff
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.ttf
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/__main__.py", line 16, in <module>
    download_scripts_and_run()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 236, in download_scripts_and_run
    main()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 220, in main
    start_server(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 55, in start_server
    app.listen(port, max_buffer_size=1024**3)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/web.py", line 2207, in listen
    server.listen(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
Checking for scripts.
It's Alive!
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/jquery@3.1.1/dist/jquery.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/js/bootstrap.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react@16.2.0/umd/react.production.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-dom@16.2.0/umd/react-dom.production.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-modal@3.1.10/dist/react-modal.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://cdn.plot.ly/plotly-2.11.1.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/sjcl@1.0.7/sjcl.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/layout-bin-packer@1.4.0/dist/layout-bin-packer.js.map
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading http://d3js.org/d3.v3.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://d3js.org/d3-selection-multi.v1.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/save-svg-as-png@1.4.17/lib/saveSvgAsPng.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-resizable@1.4.6/css/styles.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-grid-layout@0.16.3/css/styles.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/css/bootstrap.min.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/classnames@2.2.5
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/layout-bin-packer@1.4.0/dist/layout-bin-packer.js
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 0.87ms
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.eot
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.woff2
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.woff
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.ttf
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/__main__.py", line 16, in <module>
    download_scripts_and_run()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 236, in download_scripts_and_run
    main()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 220, in main
    start_server(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 55, in start_server
    app.listen(port, max_buffer_size=1024**3)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/web.py", line 2207, in listen
    server.listen(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
Checking for scripts.
It's Alive!
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/jquery@3.1.1/dist/jquery.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/js/bootstrap.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react@16.2.0/umd/react.production.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-dom@16.2.0/umd/react-dom.production.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-modal@3.1.10/dist/react-modal.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://cdn.plot.ly/plotly-2.11.1.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/sjcl@1.0.7/sjcl.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/layout-bin-packer@1.4.0/dist/layout-bin-packer.js.map
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading http://d3js.org/d3.v3.min.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://d3js.org/d3-selection-multi.v1.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/save-svg-as-png@1.4.17/lib/saveSvgAsPng.js
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-resizable@1.4.6/css/styles.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/react-grid-layout@0.16.3/css/styles.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/css/bootstrap.min.css
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/classnames@2.2.5
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/layout-bin-packer@1.4.0/dist/layout-bin-packer.js
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 1.09ms
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.eot
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.woff2
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.woff
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.ttf
ERROR:root:Error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129) while downloading https://unpkg.com/bootstrap@3.3.7/dist/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/__main__.py", line 16, in <module>
    download_scripts_and_run()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 236, in download_scripts_and_run
    main()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 220, in main
    start_server(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 55, in start_server
    app.listen(port, max_buffer_size=1024**3)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/web.py", line 2207, in listen
    server.listen(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
Checking for scripts.
It's Alive!
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 0.79ms
Traceback (most recent call last):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/__main__.py", line 16, in <module>
    exec(code, run_globals)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/__main__.py", line 16, in <module>
    download_scripts_and_run()
    download_scripts_and_run()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 236, in download_scripts_and_run
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 236, in download_scripts_and_run
    main()
    main()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 220, in main
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 220, in main
    start_server(
    start_server(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 55, in start_server
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 55, in start_server
    app.listen(port, max_buffer_size=1024**3)
    app.listen(port, max_buffer_size=1024**3)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/web.py", line 2207, in listen
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/web.py", line 2207, in listen
    server.listen(
    server.listen(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/tcpserver.py", line 183, in listen
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
    sockets = bind_sockets(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/netutil.py", line 162, in bind_sockets
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
OSError: [Errno 48] Address already in use
Checking for scripts.
It's Alive!
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/__main__.py", line 16, in <module>
    download_scripts_and_run()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 236, in download_scripts_and_run
    main()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 220, in main
    start_server(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 55, in start_server
    app.listen(port, max_buffer_size=1024**3)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/web.py", line 2207, in listen
    server.listen(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
Checking for scripts.
It's Alive!
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 0.85ms
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/__main__.py", line 16, in <module>
    download_scripts_and_run()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 236, in download_scripts_and_run
    main()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 220, in main
    start_server(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 55, in start_server
    app.listen(port, max_buffer_size=1024**3)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/web.py", line 2207, in listen
    server.listen(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
Checking for scripts.
It's Alive!
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/__main__.py", line 16, in <module>
    download_scripts_and_run()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 236, in download_scripts_and_run
    main()
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 220, in main
    start_server(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/visdom/server/run_server.py", line 55, in start_server
    app.listen(port, max_buffer_size=1024**3)
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/web.py", line 2207, in listen
    server.listen(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
  File "/Users/maksimnovozhilov/PycharmProjects/DAAOfLungPathologies/venv/lib/python3.9/site-packages/tornado/netutil.py", line 162, in bind_sockets
    sock.bind(sockaddr)
OSError: [Errno 48] Address already in use
Checking for scripts.
It's Alive!
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 1.17ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 1.24ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 3.74ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 0.95ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 0.43ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 1.07ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 0.46ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 1.14ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 0.98ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 0.91ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 1.05ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 0.85ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 0.53ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 3.49ms
INFO:tornado.access:200 POST /env/faster-rcnn (127.0.0.1) 0.95ms
